Import('*')

env.Prepend(CPPPATH=Dir('inc').srcnode())

SimObject(
    'python/LinearFunctionAccelerator.py',
    sim_objects=['LinearFunctionAccelerator'],
)
Source('src/linear_function_accelerator.cc')
